config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  root 'welcome#index'

  resources :adverse_events do
    
    resources :hum_res_assistances

    resources :hospitalization_days

    resources :ae_drugs

    resources :ae_procedures
  end  

  

  resources :branch_offices

  resources :event_categories do

    resources :events 
  end

  resources :charges

  resources :drugs do 
    collection { post :import }
    collection do        
        get 'lista_modal_medicamento'
      end    
  end

  resources :patients do
    collection do
      get 'search'
      get 'lista_modal_paciente'
    end
  end

  resources :procedures do 
    collection { post :import }
  end

  resources :services

  # You can have the root of your site routed with "root"
    
end

app/models/adverse_event.rb
# == Schema Information
#
# Table name: adverse_events
#
#  id               :integer          not null, primary key
#  time             :datetime
#  reason_admission :string
#  description      :string
#  pregnant         :boolean
#  event_id         :integer
#  patient_id       :integer
#  branch_office_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class AdverseEvent < ActiveRecord::Base
  belongs_to :event
  belongs_to :patient
  belongs_to :branch_office
  has_many :ae_drugs, dependent: :destroy
  has_many :ae_procedures, dependent: :destroy
  has_many :hospitalization_days, dependent: :destroy
  has_many :hum_res_assistances, dependent: :destroy

  validates_presence_of :patient_id
  validates_presence_of :reason_admission
  validates_presence_of :description
  validates_presence_of :event_id
  validates_presence_of :branch_office_id
end

app/controllers/adverse_events_controller.rb
class AdverseEventsController < ApplicationController
  before_action :set_adverse_event, only: [:show, :edit, :update, :destroy]
  # GET /adverse_events
  # GET /adverse_events.json
  def index
    @adverse_events = AdverseEvent.all
    @patients = Patient.all
    @branch_offices = BranchOffice.all
    @event_categories = EventCategory.all
    @events = Event.all 
  end

  # GET /adverse_events/1
  # GET /adverse_events/1.json
  def show
    @patients = Patient.all
    @branch_offices = BranchOffice.all
    @event_categories = EventCategory.all
    @events = Event.all 
    @ae_drugs = AeDrug.all
  end

  # GET /adverse_events/new
  def new
    @event_categories = EventCategory.all
    @patients = Patient.all
    @adverse_event = AdverseEvent.new
    unless params[:patient_id].nil?
      @patient = Patient.find(params[:patient_id])
      @adverse_event.patient = @patient
    end
  end

  # GET /adverse_events/1/edit
  def edit
  end

  # POST /adverse_events
  # POST /adverse_events.json
  def create
    @adverse_event = AdverseEvent.new(adverse_event_params)

    respond_to do |format|
      if @adverse_event.save
        format.html { redirect_to @adverse_event, notice: 'Evento adverso creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @adverse_event }
      else
        format.html { render :new }
        format.json { render json: @adverse_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverse_events/1
  # PATCH/PUT /adverse_events/1.json
  def update
    respond_to do |format|
      if @adverse_event.update(adverse_event_params)        
        format.html { redirect_to @adverse_event, notice: 'Evento adverso actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @adverse_event }
      else
        format.html { render :edit }
        format.json { render json: @adverse_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverse_events/1
  # DELETE /adverse_events/1.json
  def destroy
    @adverse_event.destroy
    respond_to do |format|
      format.html { redirect_to adverse_events_url, notice: 'Evento adverso eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adverse_event
      @adverse_event = AdverseEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adverse_event_params
      params.require(:adverse_event).permit(:time, :reason_admission, :description, :pregnant, :event_id, :patient_id, :branch_office_id)
    end
end

app/helpers/adverse_events_helper.rb
module AdverseEventsHelper
	def embarazada
		content_tag(:span, "SI", class: "label label-danger")
	end

	def no_embarazada
		content_tag(:span, "NO", class: "label label-success")
	end
end

app/views/adverse_events/_adverse_event.html.erb
        <tr>
          <td><%= fecha adverse_event.time %> <br> <%= hora adverse_event.time %></td> 
          <td><%= adverse_event.patient.document_number %></td>   
          <td><%= adverse_event.patient.name %> <%= adverse_event.patient.lastname %></td>                  
          <td><%= adverse_event.pregnant %></td>
          <td><%= adverse_event.event.Detail %></td>          
          <td><%= adverse_event.branch_office.name %></td>
          <td><%= link_to adverse_event, class: "btn btn-primary btn-sm" do %>
            <i class="fa fa-search"></i>
            <% end %>
          </td>
          <td><%= link_to edit_adverse_event_path(adverse_event), class: "btn btn-info btn-sm" do %>
            <i class="fa fa-pencil"></i>
            <% end %>
          </td>
          <td><%= link_to adverse_event, method: :delete, data: { confirm: '¿Seguro(a) que desea borrar?' }, class: "btn btn-danger btn-sm" do %>
            <i class="fa fa-trash"></i>
            <% end %></td>
        </tr>

app/views/adverse_events/_form.html.erb
<% unless @patient.nil? %>
  <h3>Datos del paciente</h3>
  <br>
  <div id="patient_info"> 
    <!-- Cargo los datos del paciente       -->
    <%= render partial: "patients/patient" %>
  </div>
<% else %>
  <label>Cédula del paciente</label>
  <%= form_tag(search_patients_path, method: :get, remote: true, id: "search_patient", class: "form-inline") do %>  
    <div class="form-group"> 
      <%= text_field_tag "cedula_paciente", nil, placeholder: "Número documento", class: 'form-control' %>
    </div>
      <%= submit_tag "Agregar", class: "btn btn-primary" %> <%= link_to lista_modal_paciente_patients_path, remote: true, class: "btn btn-primary" do %>
        <i class="fa fa-search"></i>
        <% end %>  
  <% end %>  
  <br>
    <div id="patient_info"> 
    <!-- Cargo los datos del paciente       -->    
    </div>     
<% end %>
<div id="modalPaciente">
      <!-- Cargo la modal  -->
</div>
<br>
<%= form_for(@adverse_event) do |f| %>
  <% if @adverse_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adverse_event.errors.count, "error") %> y el evento adverso no puede ser guardado:</h2>

      <ul>
      <% @adverse_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
        <%= f.label :time, "Fecha" %><br>
        <%= f.datetime_select :time, date_separator: "-", class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
        <%= f.label :reason_admission, "Razón de admisión:" %><br>
        <%= f.text_area :reason_admission, class: "form-control", rows: 3 %>
      </div>
    </div>    
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
        <%= f.label :description, "Descripción" %><br>
        <%= f.text_area :description, class: "form-control", rows: 3 %>
      </div>
    </div>    
  </div>
  <div class="form-group" id="embarazo">
    <div class="checkbox">
      <label>
        <%= f.check_box :pregnant %>
        <%= f.label :pregnant, "Embarazada", class: "label-control" %><br>
      </label>      
    </div>    
  </div> 
  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
        <%= f.label :event_category_id, "Categoría del evento:" %><br>
        <%= collection_select(:event_category_id, :event_category_id, EventCategory.all, :id, :name, options ={:prompt => "Seleccione una categoría"}, class: "form-control") %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
        <%= f.label :event_id, "Evento:" %><br>
        <%= collection_select(:adverse_event, :event_id, [], :id, :Detail, {}, class: "form-control" ) %>                    
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
    <%= f.label :branch_office_id, "Sucursal:" %><br>
    <%= collection_select(:adverse_event, :branch_office_id, BranchOffice.all, :id, :name, {}, class: "form-control")  %>
      </div>
    </div>
  </div>
  <div>
    <%= f.submit "Guardar", class: "btn btn-primary btn-sm"  %>
  
  <%= f.hidden_field :patient_id %>
<% end %>

app/views/adverse_events/edit.html.erb
<h1>Editar evento adverso</h1>

<%= render 'form' %>

<%= link_to 'Atrás', adverse_events_path, class: "btn btn-info btn-sm" %>
</div>
<br>
<br>

app/views/adverse_events/index.html.erb
<% provide(:title, "Evento Adverso") %>
<h1>Lista de eventos adversos</h1>
<br>
<%= link_to 'Nuevo evento adverso', new_adverse_event_path, class: "btn btn-primary btn-sm" %> <%= link_to root_path, class: "btn btn-primary pull-right"  do%>
  <i class="fa fa-home"></i>
<% end %>
<br>
<br>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Fecha</th> 
        <th>Documento</th> 
        <th>Paciente</th>              
        <th class="text-center">Embarazada?</th>
        <th>Evento</th>        
        <th>Sucursal</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @adverse_events.each do |adverse_event| %>
        <tr>
          <td><%= fecha adverse_event.time %> <br> <%= hora adverse_event.time %></td> 
          <td><%= adverse_event.patient.document_number %></td>   
          <td><%= adverse_event.patient.name %> <%= adverse_event.patient.lastname %></td>                  
          <td class="text-center"><%= adverse_event.pregnant ? embarazada : no_embarazada %></td>
          <td><%= adverse_event.event.Detail %></td>          
          <td><%= adverse_event.branch_office.name %></td>
          <td><%= link_to adverse_event, class: "btn btn-primary btn-sm" do %>
            <i class="fa fa-search"></i>
            <% end %>
          </td>
          <td><%= link_to edit_adverse_event_path(adverse_event), class: "btn btn-info btn-sm" do %>
            <i class="fa fa-pencil"></i>
            <% end %>
          </td>
          <td><%= link_to adverse_event, method: :delete, data: { confirm: '¿Seguro(a) que desea borrar?' }, class: "btn btn-danger btn-sm" do %>
            <i class="fa fa-trash"></i>
            <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Nuevo evento adverso', new_adverse_event_path, class: "btn btn-primary btn-sm" %> <%= link_to root_path, class: "btn btn-primary btn-sm pull-right"  do%>
  <i class="fa fa-home"></i>
<% end %>
<br><br>

app/views/adverse_events/new.html.erb
<h1>Crear evento adverso</h1>

<%= render 'form' %>

<%= link_to 'Atrás', adverse_events_path, class: "btn btn-info btn-sm" %>
</div>

<br>
<br>

app/views/adverse_events/show.html.erb
<% provide(:title, "Evento Adverso") %>
<h1>Detalle de evento adverso</h1>
<br>
<%= link_to 'Atrás', adverse_events_path, class: "btn btn-primary btn-sm" %> <%= link_to root_path, class: "btn btn-primary pull-right"  do%>
  <i class="fa fa-home"></i>
<% end %>
<br><br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong><%= @adverse_event.patient.document_number %> - <%= @adverse_event.patient.name %> <%= @adverse_event.patient.lastname %></strong>
    <span class="label label-success pull-right"><%= @adverse_event.branch_office.name %></span></h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Fecha</th>            
            <th class="text-center">Embarazada</th>
            <th>Categoría del evento</th>
            <th>Evento</th>
            <th colspan="3"></th>
          </tr>          
        </thead>
        <tbody>
          <tr>
            <td><%= fecha @adverse_event.time %> <br> <%= hora @adverse_event.time %></td>            
            <td class="text-center">
              <%= @adverse_event.pregnant ? embarazada : no_embarazada %>             
            </td>
            <td><%= @adverse_event.event.event_category.name %></td>
            <td><%= @adverse_event.event.Detail %></td>
            <td><%= link_to edit_adverse_event_path(@adverse_event), class: "btn btn-info btn-sm" do %>
              <i class="fa fa-pencil"></i>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table> 
      <div class="collapse" id="eventoAcordeon">     
      <table class="table">
        <thead>
          <tr>
            <th>Razón de admisión</th>
            <th>Descripción</th>
          </tr>
        </thead>
        <tbody>
          <td><%= @adverse_event.reason_admission %></td>
          <td><%= @adverse_event.description %></td>
        </tbody>
      </table> 
      </div>     
    </div>    
  </div>
  <div class="text-center" type="button" data-toggle="collapse" data-target="#eventoAcordeon" aria-expanded="false" aria-controls="eventoAcordeon"><i class="fa fa-ellipsis-h"> </i>
    <!-- <button class="btn btn-sm btn-default" </button> -->
  </div>
</div>  

<div class="panel panel-default">
  <div class="panel-heading">
    <br>
    <h3 class="panel-title"><strong>Medicamentos</strong>
    <button class="btn btn-sm btn-default pull-right" type="button" data-toggle="collapse" data-target="#medicamentosAcordeon" aria-expanded="false" aria-controls="medicamentosAcordeon"><i class="fa fa-sort-desc"> </i></button>
    </h3> 
    <br>      
  </div>
  <div class="panel-body">
    <div class="collapse" id="medicamentosAcordeon">
      <%= link_to new_adverse_event_ae_drug_path(@adverse_event), class: "btn btn-primary btn-sm" do %>
        <i class="fa fa-plus-circle"><span></span>  Agregar Medicamento</i> 
      <% end %>  

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Medicamento</th>
              <th>Cantidad</th>
              <th>Precio</th>
              <th>Cargo</th>
              <th>Servicio</th>
              <th>Subtotal</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @adverse_event.ae_drugs %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td><span class="label label-info">Total:</span></td>
              <td><%= number_to_currency(@adverse_event.ae_drugs.sum(:drug_subtotal), delimiter: ".") %></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <br>
    <h3 class="panel-title"><strong>Procedimientos</strong>
    <button class="btn btn-sm btn-default pull-right" type="button" data-toggle="collapse" data-target="#procedimientosAcordeon" aria-expanded="false" aria-controls="procedimientosAcordeon"><i class="fa fa-sort-desc"> </i></button>
    </h3> 
    <br>      
  </div>
  <div class="panel-body">
    <div class="collapse" id="procedimientosAcordeon">
      <%= link_to new_adverse_event_ae_procedure_path(@adverse_event), class: "btn btn-primary btn-sm" do %>
          <i class="fa fa-plus-circle"><span></span>  Agregar procedimiento</i>  
      <% end %>  
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Tiempo</th>
              <th>Procedimiento</th>
              <th>Precio</th>
              <th>Servicio</th>
              <th>Cargo</th>  
              <th>Subtotal</th>      
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @adverse_event.ae_procedures %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td><span class="label label-info">Total:</span></td>
              <td><%= number_to_currency(@adverse_event.ae_procedures.sum(:procedure_price), delimiter: ".") %></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <br>
    <h3 class="panel-title"><strong>Recursos humanos asistenciales</strong>
    <button class="btn btn-sm btn-default pull-right" type="button" data-toggle="collapse" data-target="#RHAAcordeon" aria-expanded="false" aria-controls="RHAAcordeon"><i class="fa fa-sort-desc"> </i></button>
    </h3> 
    <br>      
  </div>
  <div class="panel-body">
    <div class="collapse" id="RHAAcordeon">
      <%= link_to new_adverse_event_hum_res_assistance_path(@adverse_event), class: "btn btn-primary btn-sm" do %>
        <i class="fa fa-plus-circle"><span></span>  Agregar Recurso humano asistencial</i>  
      <% end %>  
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Nombre</th>
              <th>Cantidad</th>
              <th>Precio</th>
              <th>Servicio</th>
              <th>Subtotal</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @adverse_event.hum_res_assistances %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td><span class="label label-info">Total:</span></td>
              <td><%= number_to_currency(@adverse_event.hum_res_assistances.sum(:subtotal), delimiter: ".") %></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <br>
    <h3 class="panel-title"><strong>Días de estancia</strong>
    <button class="btn btn-sm btn-default pull-right" type="button" data-toggle="collapse" data-target="#diasAcordeon" aria-expanded="false" aria-controls="diasAcordeon"><i class="fa fa-sort-desc"> </i></button>
    </h3> 
    <br>      
  </div>
  <div class="panel-body">
    <div class="collapse" id="diasAcordeon">
      <%= link_to new_adverse_event_hospitalization_day_path(@adverse_event), class: "btn btn-primary btn-sm" do %>
        <i class="fa fa-plus-circle"><span></span>  Agregar Día de estancia</i>  
      <% end %>  
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Cantidad</th>
              <th>Precio</th>
              <th>Servicio</th>
              <th>Subtotal</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @adverse_event.hospitalization_days %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td><span class="label label-info">Total:</span></td>
              <td><%= number_to_currency(@adverse_event.hospitalization_days.sum(:subtotal), delimiter: ".") %></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<%= link_to 'Atrás', adverse_events_path, class: "btn btn-primary btn-sm" %> <%= link_to root_path, class: "btn btn-primary btn-sm pull-right"  do%>
  <i class="fa fa-home"></i>
<% end %>
<br><br>