config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  root 'welcome#index'

  resources :adverse_events do
    
    resources :hum_res_assistances

    resources :hospitalization_days

    resources :ae_drugs

    resources :ae_procedures
  end  

  

  resources :branch_offices

  resources :event_categories do

    resources :events 
  end

  resources :charges

  resources :drugs do 
    collection { post :import }
    collection do        
        get 'lista_modal_medicamento'
      end    
  end

  resources :patients do
    collection do
      get 'search'
      get 'lista_modal_paciente'
    end
  end

  resources :procedures do 
    collection { post :import }
  end

  resources :services

  # You can have the root of your site routed with "root"
    
end

app/models/event_category.rb
# == Schema Information
#
# Table name: event_categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EventCategory < ActiveRecord::Base
	has_many :events, dependent: :destroy

	validates_presence_of :name
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  before_action :set_event_category, only: [:show, :edit, :update, :destroy]

  # GET /event_categories
  # GET /event_categories.json
  def index
    @event_categories = EventCategory.all
  end

  # GET /event_categories/1
  # GET /event_categories/1.json
  def show
  end

  # GET /event_categories/new
  def new
    @event_category = EventCategory.new
  end

  # GET /event_categories/1/edit
  def edit
  end

  # POST /event_categories
  # POST /event_categories.json
  def create
    @event_category = EventCategory.new(event_category_params)

    respond_to do |format|
      if @event_category.save
        format.html { redirect_to @event_category, notice: 'Categoría del evento ingresada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @event_category }
      else
        format.html { render :new }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_categories/1
  # PATCH/PUT /event_categories/1.json
  def update
    respond_to do |format|
      if @event_category.update(event_category_params)
        format.html { redirect_to @event_category, notice: 'Categoría del evento actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @event_category }
      else
        format.html { render :edit }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_categories/1
  # DELETE /event_categories/1.json
  def destroy
    @event_category.destroy
    respond_to do |format|
      format.html { redirect_to event_categories_url, notice: 'Categoría del evento eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_category
      @event_category = EventCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_category_params
      params.require(:event_category).permit(:name)
    end
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/views/event_categories/_form.html.erb
<%= form_for(@event_category) do |f| %>
  <% if @event_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_category.errors.count, "error") %> y la categoría del evento no puede ser guardada:</h2>

      <ul>
      <% @event_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-md-6 col-lg-6">
        <%= f.label :name, "Nombre" %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary btn-sm" %>
  
<% end %>

app/views/event_categories/edit.html.erb
<h1>Editar categoría de evento</h1>

<%= render 'form' %>

<%= link_to 'Atrás', event_categories_path, class: "btn btn-info btn-sm" %>
</div>
<br><br>

app/views/event_categories/index.html.erb
<% provide(:title, "Categoría de eventos") %>
<h1>Lista de categorías de eventos</h1>
<br>
<div class="row">
  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= link_to 'Crear categoría de evento', new_event_category_path, class: "btn btn-primary" %>
  </div>
  <div class="col-sm-4 col-md-4 col-lg-4">
    <div class="input-group">
      <%= text_field_tag "filter", nil, class: "form-control", placeholder: "Buscar..." %>
      <span class="input-group-btn">
        <%= link_to nil, class: "btn btn-primary" do  %> 
        <i class="fa fa-search"></i>
        <% end %>
      </span>      
    </div>
  </div>
  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= link_to root_path, class: "btn btn-primary pull-right" do %>
      <i class="fa fa-home"></i>  
    <% end %>     
  </div>
</div>
 
<br>
<br>
<div class="responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="searchable">
      <% @event_categories.each do |event_category| %>
        <tr>
          <td><%= event_category.name %></td>
          <td><%= link_to event_category, class: "btn btn-primary btn-sm" do %>
                <i class="fa fa-search"></i>  
              <% end %>  
          </td>
          <td><%= link_to edit_event_category_path(event_category), class: "btn btn-info btn-sm" do %>
                <i class="fa fa-pencil"></i>  
              <% end %>  </td>
          <td><%= link_to event_category, method: :delete, data: { confirm: '¿Está seguro(a) que quiere eliminar?' }, class: "btn btn-danger btn-sm" do %>
                <i class="fa fa-trash"></i>  
              <% end %>  </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Crear categoría de evento', new_event_category_path, class: "btn btn-primary" %>
<br>
<br>

app/views/event_categories/new.html.erb
<h1>Crear categoría de evento</h1>

<%= render 'form' %>

<%= link_to 'Atrás', event_categories_path, class: "btn btn-info btn-sm" %>
</div>
<br>
<br>

app/views/event_categories/show.html.erb
<% provide(:title, "Categoría de eventos") %>
<h1>Categoría del evento</h1>
<br>
<%= link_to 'Atrás', event_categories_path, class: "btn btn-primary btn-sm" %> <%= link_to root_path, class: "btn btn-primary pull-right"  do%>
  <i class="fa fa-home"></i>
<% end %>
<br>
<br>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Nombre</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @event_category.name %></td>
				<td class="pull-right"><%= link_to edit_event_category_path(@event_category), class: "btn btn-info btn-sm" do %>
		                <i class="fa fa-pencil"></i>  
		            <% end %>
		        </td>
			</tr>
		</tbody>
	</table>
</div>
<br>
<h3>Detalle</h3>
<%= link_to new_event_category_event_path(@event_category), class: "btn btn-primary btn-sm" do %>
  <i class="fa fa-file-text"><span>  Agregar detalle</span></i>  
<% end %>  
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<%= render @event_category.events %>
		</tbody>
	</table>
</div>
<br>

<%= link_to 'Atrás', event_categories_path, class: "btn btn-primary btn-sm" %>