config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  root 'welcome#index'

  resources :adverse_events do
    
    resources :hum_res_assistances

    resources :hospitalization_days

    resources :ae_drugs

    resources :ae_procedures
  end  

  

  resources :branch_offices

  resources :event_categories do

    resources :events 
  end

  resources :charges

  resources :drugs do 
    collection { post :import }
    collection do        
        get 'lista_modal_medicamento'
      end    
  end

  resources :patients do
    collection do
      get 'search'
      get 'lista_modal_paciente'
    end
  end

  resources :procedures do 
    collection { post :import }
  end

  resources :services

  # You can have the root of your site routed with "root"
    
end

app/models/ae_drug.rb
# == Schema Information
#
# Table name: ae_drugs
#
#  id               :integer          not null, primary key
#  drug_price       :float
#  drug_subtotal    :float
#  drug_time        :datetime
#  qty              :integer
#  adverse_event_id :integer
#  drug_id          :integer
#  service_id       :integer
#  charge_id        :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class AeDrug < ActiveRecord::Base
  belongs_to :adverse_event
  belongs_to :drug
  belongs_to :service
  belongs_to :charge
  before_save :calcular_subtotal

  def calcular_subtotal
  	self.drug_subtotal = self.drug_price * self.qty    
  end  

  validates_presence_of :drug_price
  validates_presence_of :qty
  validates_presence_of :service_id
  validates_presence_of :charge_id
end

app/controllers/ae_drugs_controller.rb
class AeDrugsController < ApplicationController
  before_action :set_ae_drug, only: [:show, :edit, :update, :destroy]
  before_action :set_adverse_event

  # GET /ae_drugs
  # GET /ae_drugs.json
  def index
    @ae_drugs = AeDrug.all
  end

  # GET /ae_drugs/1
  # GET /ae_drugs/1.json
  def show
   
  end

  # GET /ae_drugs/new
  def new
    @ae_drug = @adverse_event.ae_drugs.build
    @drugs = Drug.all
  end

  # GET /ae_drugs/1/edit
  def edit
    @drugs = Drug.all
  end

  # POST /ae_drugs
  # POST /ae_drugs.json
  def create
    @drugs = Drug.all
    @ae_drug = @adverse_event.ae_drugs.create(ae_drug_params)

    respond_to do |format|
      if @ae_drug.save
        format.html { redirect_to adverse_event_path(@adverse_event), notice: 'Medicamento suministrado, ingresado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @ae_drug }       
      else
        format.html { render :new }
        format.json { render json: @ae_drug.errors, status: :unprocessable_entity }        
      end
    end
  end

  # PATCH/PUT /ae_drugs/1
  # PATCH/PUT /ae_drugs/1.json
  def update
    @drugs = Drug.all
    respond_to do |format|
      if @ae_drug.update(ae_drug_params)
        format.html { redirect_to adverse_event_path(@adverse_event), notice: 'Medicamento suministrado, actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @ae_drug }
      else
        format.html { render :edit }
        format.json { render json: @ae_drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ae_drugs/1
  # DELETE /ae_drugs/1.json
  def destroy
    @ae_drug.destroy
    respond_to do |format|
      format.html { redirect_to ae_drugs_url, notice: 'Medicamento suministrado, eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ae_drug
      @ae_drug = AeDrug.find(params[:id])
    end

    def set_adverse_event
      @adverse_event = AdverseEvent.find(params[:adverse_event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ae_drug_params
      params.require(:ae_drug).permit(:drug_price, :drug_subtotal, :drug_time, :qty, :adverse_event_id, :drug_id, :service_id, :charge_id)
    end
end

app/helpers/ae_drugs_helper.rb
module AeDrugsHelper
end

app/views/ae_drugs/_ae_drug.html.erb
<tr>
  <td><%= fecha ae_drug.drug_time %> <br> <%= hora ae_drug.drug_time %></td>
  <td><%= ae_drug.drug.name %></td>
  <td><%= ae_drug.qty %></td>
  <td><%= number_to_currency(ae_drug.drug_price, delimiter: ".") %></td>
  <td><%= ae_drug.service.name %></td>
  <td><%= ae_drug.charge.name %></td>  
  <td><%= number_to_currency(ae_drug.drug_subtotal, delimiter: ".") %></td>
  <td ><%= link_to edit_adverse_event_ae_drug_path(ae_drug.adverse_event,ae_drug), class: "btn btn-info btn-sm pull-right" do %>
    <i class="fa fa-pencil"></i>
    <% end %>
  </td>  
</tr> 

app/views/ae_drugs/_form.html.erb
<h4><span class="label label-success"><%= @adverse_event.patient.document_number %> <%= @adverse_event.patient.name %> <%= @adverse_event.patient.lastname %></span></h4>
<div id="modalMedicamentos">
  
</div>
<%= form_for([@adverse_event,@ae_drug]) do |f| %>
  <% if @ae_drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ae_drug.errors.count, "error") %> y el medicamento suministrado no puede ser guardado:</h2>

      <ul>
      <% @ae_drug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-md-4 col-lg-4">
        <%= f.label :drug_time, "Fecha" %><br>
        <%= f.datetime_select :drug_time, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-5 col-lg-5">
        <%= label_tag :drug_name, "Medicamento" %><br>
        <div class="input-group">        
          <%= text_field_tag :drug_name, [], id: "nombre", class: "form-control", disabled: true %>
          <span class="input-group-btn">
            <%= link_to lista_modal_medicamento_drugs_path, remote: true, class: "btn btn-primary" do  %> 
            <i class="fa fa-search"></i>
            <% end %>
          </span>      
        </div>               
      </div>         
    </div>    
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-1 col-lg-1">
        <%= f.label :qty, "Cantidad" %><br>
        <%= f.number_field :qty, class: "form-control" %>
      </div>
    </div>    
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-2 col-lg-2">
        <%= f.label :drug_price, "Precio" %><br>
        <%= f.text_field :drug_price, class: "form-control", :readonly => true %>
      </div>
    </div>    
  </div> 
  <div class="form-group">
    <div class="row">
      <div class="col-md-4 col-lg-4">
        <%= f.label :service_id, "Servicio" %><br>
        <%= collection_select(:ae_drug, :service_id, Service.all, :id, :name, {}, class: "form-control") %>
      </div>
    </div>    
  </div>  
  <div class="form-group">
    <div class="row">
      <div class="col-md-4 col-lg-4">
        <%= f.label :charge_id, "Cargo" %><br>
        <%= collection_select(:ae_drug, :charge_id, Charge.all, :id, :name, {}, class: "form-control") %>
      </div>
    </div>    
  </div>  
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary btn-sm" %>
  
  <%= f.hidden_field :adverse_event_id %>
  <%= f.hidden_field :drug_id %>
<% end %>

app/views/ae_drugs/edit.html.erb
<h1>Editar medicamento</h1>

<%= render 'form' %>

<%= link_to 'Atrás', adverse_event_path(@adverse_event), class: "btn btn-info btn-sm" %>
</div>
<br>
<br>

app/views/ae_drugs/index.html.erb
<h1>Listado de medicamentos</h1>

<table>
  <thead>
    <tr>
      <th>Precio</th>
      <th>Subtotal</th>
      <th>Fecha</th>
      <th>Cantidad</th>
      <th>Evento adverso</th>
      <th>Medicamento</th>
      <th>Servicio</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ae_drugs.each do |ae_drug| %>
      <tr>
        <td><%= ae_drug.drug_price %></td>
        <td><%= ae_drug.drug_subtotal %></td>
        <td><%= ae_drug.drug_time %></td>
        <td><%= ae_drug.qty %></td>
        <td><%= ae_drug.adverse_event %></td>
        <td><%= ae_drug.drug %></td>
        <td><%= ae_drug.service %></td>
        <td><%= ae_drug.charge %></td>
        <td><%# link_to 'Ver', ae_drug %></td>
        <td><%# link_to 'Editar', edit_ae_drug_path(ae_drug) %></td>
        <td><%= link_to 'Eliminar', ae_drug, method: :delete, data: { confirm: '¿Está seguro(a) que quiere eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo medicamento', new_ae_drug_path %>

app/views/ae_drugs/new.html.erb
<h1>Nuevo medicamento</h1>

<%= render 'form' %>

<%= link_to 'Atrás', adverse_event_path(@adverse_event), class: "btn btn-info btn-sm" %>
</div>
<div>
  <%= render partial: "drugs/listado_medicamentos" %>
</div>
<br>
<br>

app/views/ae_drugs/show.html.erb
<p>
  <strong>Precio:</strong>
  <%= @ae_drug.drug_price %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @ae_drug.drug_subtotal %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @ae_drug.drug_time %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @ae_drug.qty %>
</p>

<p>
  <strong>Evento adverso:</strong>
  <%= @ae_drug.adverse_event %>
</p>

<p>
  <strong>Medicamento:</strong>
  <%= @ae_drug.drug %>
</p>

<p>
  <strong>Servicio:</strong>
  <%= @ae_drug.service_id %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @ae_drug.charge %>
</p>

<%= link_to 'Editar', edit_adverse_event_ae_drug_path(@ae_drug.adverse_event,@ae_drug) %> |
<%= link_to 'Atrás', adverse_event_path(@adverse_event) %>