config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  root 'welcome#index'

  resources :adverse_events do
    
    resources :hum_res_assistances

    resources :hospitalization_days

    resources :ae_drugs

    resources :ae_procedures
  end  

  

  resources :branch_offices

  resources :event_categories do

    resources :events 
  end

  resources :charges

  resources :drugs do 
    collection { post :import }
    collection do        
        get 'lista_modal_medicamento'
      end    
  end

  resources :patients do
    collection do
      get 'search'
      get 'lista_modal_paciente'
    end
  end

  resources :procedures do 
    collection { post :import }
  end

  resources :services

  # You can have the root of your site routed with "root"
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% provide(:title, "Inicio") %>
<h1>Bienvenidos a Sispea</h1>
<h5>Tú solución administrativa en salud</h5>
<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<div class="offer offer-radius offer-primary">
					<div class="shape">
						<div class="shape-text">
							Ver
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Pacientes
						</h3>
						<p>
							Lista de todos los pacientes.
							<br> <br>
							<p class="text-center">
								<%= link_to patients_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>							  
						</p>
					</div>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="offer offer-radius offer-info">
					<div class="shape">
						<div class="shape-text">
							Ver								
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Servicios
						</h3>						
						<p>
							Lista de los servicios prestados.
							<br> <br>
							<p class="text-center">
								<%= link_to services_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="offer offer-radius offer-primary">
					<div class="shape">
						<div class="shape-text">
							Ver								
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Cargos
						</h3>						
						<p>
							Lista de los cargos del personal que presta el servicio.
							<p class="text-center">
								<%= link_to charges_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="offer offer-radius offer-info">
					<div class="shape">
						<div class="shape-text">
							Ver							
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Lista de eventos
						</h3>						
						<p>
							Lista de las categorias de eventos y su detalle.
							<br>
							<p class="text-center">
								<%= link_to event_categories_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>
        </div>
        <div class="row">
			<div class="col-xs-3">
				<div class="offer offer-radius offer-info">
					<div class="shape">
						<div class="shape-text">
							Ver							
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Medicamentos
						</h3>						
						<p>
							Lista de medicamentos disponibles
							<br><br>
							<p class="text-center">
								<%= link_to drugs_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="offer offer-radius offer-primary">
					<div class="shape">
						<div class="shape-text">
							Ver							
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Procedimientos
						</h3>						
						<p>
							Lista de procedimientos disponibles
							<br>
							<p class="text-center">
								<%= link_to procedures_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="offer offer-radius offer-info">
					<div class="shape">
						<div class="shape-text">
							Ver							
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Eventos adversos
						</h3>						
						<p>
							Lista de eventos adversos registrados
							<br>
							<p class="text-center">
								<%= link_to adverse_events_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>
			<div class="col-xs-3">
				<div class="offer offer-radius offer-primary">
					<div class="shape">
						<div class="shape-text">
							Ver							
						</div>
					</div>
					<div class="offer-content">
						<h3 class="lead">
							Sedes
						</h3>						
						<p>
							Lista de sedes o sucursales de la entidad
							<br>
							<p class="text-center">
								<%= link_to branch_offices_path , class: "btn btn-primary btn-lg" do %>
  									<i class="fa fa-search"><span>  VER</span></i>  
								<% end %>
							</p>
						</p>
					</div>
				</div>
			</div>	
		</div>
	</div>
<p></p>